---

# ------------------------------------------------------------------------------
# Digital Ocean API Token
do_api_token: b8eaa27705e0dbfa2f55644d233eed1ea905acea887b30acc622574a0e22d116


# ------------------------------------------------------------------------------
# Digital Ocean SSH Key
do_ssh_key_name: stor.guru.key
do_ssh_key_rsa: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpQIBAAKCAQEAw2Mi55qdq835bTNa4pg9B8zBlrxmjXYJU+IFydHtR6O3XnzH
  +/Je/0qKSV296Dfw5f/BaiNughEK54PjOKa8iseY4hd0vAB5JN9T2gUo4pJttSgb
  CaElBgXsigs7D6+FRzLpap9dJniHaLyfCR+lz9Jbe/Q79iDnYsoXQUL2jzP1DS4P
  PuR6uS9eCFyPfHuKNxQ3vhT2dGJiLkTMlEp9gsZIiRUiqRxgECzmQP0MmKHOjNbj
  ybAXq9oVIfSbrCAuQ3QY+QQf0p+/Tktn09GJTHhRzgux/Qb1ykluYF+EbAbKjZ+S
  LjGj4nRkzJdbGybAX86z/Mdad+AwNXmhgzRZGQIDAQABAoIBABWe3rnqLhBY1oTy
  7detKPO4AKQBbQeyTA3wMNvIUw1eXGgkPqzugPyW7v53VRBhQFLzHh/0k8HoyOAd
  hAM80Bg7RfuexNgY5U7jN5AkigWoVmN5cKR8JHCqLyaHX524unLKe3HE+LXNGI7K
  cH699ccta9oniIsP0QrpefFKy6XE1JXe7v9WkTZwCtaVEAvNaHo244DnLoq+yuIV
  +iekoej128K+atkElKoqLjpTnjCI9QNBD5ASpqBRWprxYq7zVEaLPCtLDwtAXsMk
  H1d15q9tyK6vdQsuWA/TuaFKSnCqE9PY869Mgauw3KLH1GjXmae0wvr0D80zFDNS
  yGu+MgECgYEA374RnQZCFidYj0GnKbFA6lx19S/1BXFerlC5zFV5CpoF/9NfNmGV
  hT9Fc7/3/yhdl+hVf+Aio4UJuX/MHAam9tgIXMzM+vrH9iAzT3MoOsHANDl1I/Re
  5ylsanvAIjtF0gcKb54Jao2jw9hOWVwhqImrhzUPnRJFhQzKMeDTzskCgYEA346H
  KiC3RXg8tfkfEMJsUVvXPsAEAMInyv3ZE9C5G3La8iGnUqvM+RPf8x8Z7qao1g18
  oZPn3oNxggeu3azi3PvjYQIF7EfWTYEE8fw4+aHcHkUWEfcHHPRSTZCcJTpWWHm0
  o8Elyg6MRnTDURQF/k2miiAAyRJ5uBCTWId0z9ECgYEAxQVsISfXngZ7t3qKpu4N
  SdKtlIDsdCSGyV0Qn1xMwActbT9GQm7f6Xvzvp+21BtJf3D5iSdnmTKXg5+DrtI0
  yH0nsAAwKHoZByUHydiP/l2K0PIfss+HmmshqwrZ/8rOCspkaDFz/T5IjTa2l33H
  rc+9GcyhuSDT0vuWOSHPofECgYEAmSdpziCvrfYbkYdkEvU/g9VpduHRXDunS1fx
  ObQKvJVJDgykNuzf9dv51vN9rpOao1qGAaP0e+qM/soIsHFa0o32TmU2bZMha+Nx
  4d4rokmTJWGrJw+XXey73cuuTYrT0LVAXdda7jxdOX+Qt6ECIiBMceBO6XGw1br1
  VvclvaECgYEA09RVQ5wfmMWohlqCGud/m1GyjAHDyNQN1fOZQ1MSrvdz52Mc8Fsv
  /mIXv0j5arY37hqFv7dzRgeIycPQhMr8VBkOhnhGYdXUd5Ab3iGfhRAj0pGld6hr
  Mg2d4v5B/6KdekbuQfP6rgLctoDjczLbA4NOxMXA3+XJVBOEipjUaY0=
  -----END RSA PRIVATE KEY-----

do_ssh_key_pub: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDYyLnmp2rzfltM1rimD0HzMGWvGaNdglT4gXJ0e1Ho7defMf78l7/SopJXb3oN/Dl/8FqI26CEQrng+M4pryKx5jiF3S8AHkk31PaBSjikm21KBsJoSUGBeyKCzsPr4VHMulqn10meIdovJ8JH6XP0lt79Dv2IOdiyhdBQvaPM/UNLg8+5Hq5L14IXI98e4o3FDe+FPZ0YmIuRMyUSn2CxkiJFSKpHGAQLOZA/QyYoc6M1uPJsBer2hUh9JusIC5DdBj5BB/Sn79OS2fT0YlMeFHOC7H9BvXKSW5gX4RsBsqNn5IuMaPidGTMl1sbJsBfzrP8x1p34DA1eaGDNFkZ dylan@DZLaptop

do_ssh_key_pub_file: "{{ lookup('env','HOME') }}/.ssh/stor.guru.key.pub"
do_ssh_key_file: "{{ lookup('env','HOME') }}/.ssh/stor.guru.key"
do_ssh_key_fingerprint: 5c:81:8e:03:c4:19:63:52:57:2a:20:9d:6a:8a:22:3d


# ------------------------------------------------------------------------------
# Digital Ocean Droplet Configuration
do_droplet_name: zinglax
do_droplet_size: 512mb
do_droplet_region: nyc3
do_droplet_image: ubuntu-16-04-x64


# ------------------------------------------------------------------------------
# Digital Ocean Domain Configuration
do_domain_name: zinglax.com


# ------------------------------------------------------------------------------
# stor.guru user
nonroot_user: dylan 


# ------------------------------------------------------------------------------
# stor.guru user password
nonroot_password: f3fk!@Kkkek8873de


# ------------------------------------------------------------------------------
# stor.guru user description/comment
nonroot_comment: This user will manage the zinglax host server.


# ------------------------------------------------------------------------------
# apache2 deployment root
apache_deployment: /var/www


# ------------------------------------------------------------------------------
# apache2 Port
http_port: 80